// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4aAtoRkanf6JI0szdJAwaME1-S4mW8Tg',
    appId: '1:744877468375:web:0a76932f0615c1bd161e92',
    messagingSenderId: '744877468375',
    projectId: 'fir-flutter-e568a',
    authDomain: 'fir-flutter-e568a.firebaseapp.com',
    storageBucket: 'fir-flutter-e568a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJw3568laBuBFpUhzoNMyX0EIywhxk7a0',
    appId: '1:744877468375:android:476997e60ec78b44161e92',
    messagingSenderId: '744877468375',
    projectId: 'fir-flutter-e568a',
    storageBucket: 'fir-flutter-e568a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhNF1bn1yuGZp-ro8XCSZG8o_pGrfo8r0',
    appId: '1:744877468375:ios:3c3832002ca05766161e92',
    messagingSenderId: '744877468375',
    projectId: 'fir-flutter-e568a',
    storageBucket: 'fir-flutter-e568a.firebasestorage.app',
    iosBundleId: 'com.example.bmiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhNF1bn1yuGZp-ro8XCSZG8o_pGrfo8r0',
    appId: '1:744877468375:ios:3c3832002ca05766161e92',
    messagingSenderId: '744877468375',
    projectId: 'fir-flutter-e568a',
    storageBucket: 'fir-flutter-e568a.firebasestorage.app',
    iosBundleId: 'com.example.bmiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4aAtoRkanf6JI0szdJAwaME1-S4mW8Tg',
    appId: '1:744877468375:web:ca671d76005e41a6161e92',
    messagingSenderId: '744877468375',
    projectId: 'fir-flutter-e568a',
    authDomain: 'fir-flutter-e568a.firebaseapp.com',
    storageBucket: 'fir-flutter-e568a.firebasestorage.app',
  );
}
